server.port=8761
spring.application.name=EUREKA-SERVER

# Do not register itself as this IS the registry, not a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Don't wait for other replicas to sync on startup (single-instance mode)
eureka.server.wait-time-in-ms-when-sync-empty=0

# Logging
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
logging.pattern.console=%d{HH:mm:ss} %-5level [%logger{36}] - %msg%n